### ISSUE TITLE
Firefox 101 killed TMP

### ISSUE THREAD

**Issue by lanx73** [onemen/TabMixPlus#145]
Hi, just updated Firefox to version 101 and TMP got permanently disabled since the userChromeJS scripts are no longer initialized. 😱😭

**Comment by onemen** [comment]
Try to update to userChromeJS scripts latest vesion

**Comment by cxen** [comment]
Same issue here. I checked that I have the latest userChromeJS files, making sure I followed the instructions here https://github.com/xiaoxiaoflood/firefox-scripts.

I can see the UserScripts menu in the hamburger menu but TMP does not load.

**Comment by onemen** [comment]
I'm using Firefox nightly 103 without any issue with Tab mix and firefox-scripts

report about this issue to @xiaoxiaoflood in https://github.com/xiaoxiaoflood/firefox-scripts

make sure to use step 6 form firefox-scripts Instructions:
Open **about:support** and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup.

**Comment by Manimap** [comment]
I had the exact same problem since update to 101.
I updated the firefox-scripts, but I still couldn't activate the addon.
What did the trick was simply reinstalling the xpi file of the latest version, it activated by itself.

**Comment by Mrsash2020** [comment]
> Hi.
> 
> Install https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/fx-folder.zip to Mozilla Firefox in program files folder. Restart FF and install drag&drop tab_mix_plus-dev-build.xpi. After this TMP in FF 101 work!

Ok that worked for me after the initial shock. Thanks for the tip.

**Comment by dv8472** [comment]
> Hi.
> 
> Install https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/fx-folder.zip to Mozilla Firefox in program files folder. Restart FF and install drag&drop tab_mix_plus-dev-build.xpi. After this TMP in FF 101 work!

thx, worked for me as well!

**Comment by dwd1** [comment]
> Hi.
> 
> Install https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/fx-folder.zip to Mozilla Firefox in program files folder. Restart FF and install drag&drop tab_mix_plus-dev-build.xpi. After this TMP in FF 101 work!

not working for me, it says This add-on could not be installed because it appears to be corrupt.

**Comment by onemen** [comment]
> not working for me, it says This add-on could not be installed because it appears to be corrupt.

You only see this message when you don't have [userChromeJS](https://github.com/xiaoxiaoflood/firefox-scripts#instructions) installed properly.

**Comment by chimalek** [comment]
> not working for me, it says This add-on could not be installed because it appears to be corrupt.

Install https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/fx-folder.zip to Mozilla Firefox folder.

**Comment by mimteatr** [comment]
Hey,

Using FF 102.0b9 (64-bit) and it definitely doesn't work - add-on isn't signed

No matter what people advise to do here - nothing works:
1. _update  latest userChromeJS files_ - I happen to use many of the scripts there, and they're pretty updated (although there weren't any real updates for quite some time there!), and still downloaded and reinstalled again just to comply here, but no result!
2. _Install fx-folder.zip_ - Obviously it's installed, otherwise the scripts mentioned above wouldn't work!
3. _Open about:support and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup_ - obviously!
4. __drag&drop tab_mix_plus-dev-build.xpi_. - obviously!

**Conclusion - FF killed TabMixPlus** 😡😥

**Comment by xiaoxiaoflood** [comment]
I believe he uses Beta instead of Developer Edition, what I use and recommend. DevEd uses the exact same base version as Beta, but have unlocked flags for things like installing unsigned addons. A *hack* is needed to bypass this restriction in release, Beta and ESR and it's expected that Firefox eventually breaks this kind of thing. That's what happened recently, the previous hack doesn't work anymore:
https://github.com/xiaoxiaoflood/firefox-scripts/blob/ad2061bdaa9a5f77967029741a16614699a99f3a/installation-folder/config.js#L4-L13

So now a different bypass method is being used. In case of any issue, user should update every related files, not just  userChromeJS. In this case, the key file that needs to be updated is [config.js](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/installation-folder/config.js) (which is part of `fx-folder.zip`).

**Comment by onemen** [comment]
@xiaoxiaoflood,

This code looks simpler, what do you think?
It only update `AppConstants.jsm` without changing any other global function.

```js
const Constants = ChromeUtils.import("resource://gre/modules/AppConstants.jsm");
const temp = Object.assign({}, Constants.AppConstants);
temp.MOZ_REQUIRE_SIGNING = false
Constants.AppConstants = Object.freeze(temp);
```

**Comment by onemen** [comment]
@Manimap

I have no intention to patronize anyone.

**Comment by xiaoxiaoflood** [comment]
> This code looks simpler, what do you think?

It really works, thanks. Done in https://github.com/xiaoxiaoflood/firefox-scripts/commit/7f4e96000baf44398e7308b0aed24781ec29ea82.

**Comment by Manimap** [comment]
> @Manimap
> 
> I have no intention to patronize anyone.

I think you @ the wrong person :)

**Comment by megaslx** [comment]
> Hi, just updated Firefox to version 101 and TMP got permanently disabled since the userChromeJS scripts are no longer initialized. 😱😭

my procedure is:
1. remove chrome folder's files,restart firefox and uninstall old tmp addon(if you installed one)
2. place script only zip's files into chrome folder,start firefox and clear startup cache in support page,it will restart firefox.
3. make sure your scripts are working fine,then close firefox,place script and extension zip's files into chrome folder,start your firefox,try install tmp,now you will find ff doesn't say the addon file is broken anymore.
