### ISSUE TITLE
Multi-row not working

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#16]
![image](https://user-images.githubusercontent.com/3650909/105495577-0230d700-5cc5-11eb-967e-b2bfa3ce2e8c.png)

I will work on this one

**Comment by onemen** [comment]
this error is related, since we don't have _scrollbox
```
Uncaught TypeError: can't access property "scrollLeft", tabstrip._scrollbox is undefined
    afterTabTitleChanged chrome://tabmixplus/content/places/places.js:554
    TMP_onTabTitleChanged chrome://tabmixplus/content/minit/tablib.js:1844
    _setTabLabel chrome://tabmixplus/content/changecode.js line 218 > eval:32
    setTabTitle chrome://tabmixplus/content/changecode.js line 218 > eval:65
    onLocationChange chrome://browser/content/tabbrowser.js:6204

```
i added this at the top of tabsBindings.js
```js
  // temporary workaround until we fix multi-row feture
  if (!gBrowser.tabContainer.arrowScrollbox._scrollbox) {
    gBrowser.tabContainer.arrowScrollbox._scrollbox = {};
  }
```

**Comment by 117649** [comment]
mat be use 'gBrowser.tabContainer.arrowScrollbox.scrollbox'?

**Comment by onemen** [comment]
I need to work on converting scrollbox.xml to extend MozArrowScrollbox

**Comment by 117649** [comment]
> I need to work on converting scrollbox.xml to extend MozArrowScrollbox

https://bgrins.github.io/xbl-analysis/converter/
This site just come in handy for generate CE from XBL.
Just copy paste XML into left box and you get JS from right box.
You still have to tinker here and there though but its much easier.

Base on how shadow [DOM slot works](https://javascript.info/slots-composition#default-slot-first-unnamed) the process could be as much simple as:

1. once you have the Custom Element ready define it to still use the \<scrollbox\> tag.
2. In shadow-root of the \<arrowscrollbox\> create a instance of your \<scrollbox\> with a \<html:slot\> child.
3. Insert the created \<scrollbox\> before the original one thus it should automatically replace the older.
4. Remove the old element. 

I leave it untouched when I was converting the tab bindings because I have no idea how multi-row and scroll box binding works.

**Comment by onemen** [comment]
Thank you for the tip @117649, i will look into it later today

**Comment by 117649** [comment]
I'm sorry, I wasn't quite understand what 'scrollbox.xml' is doing back then thus my advice may be misleading.
Its looks like 'scrollbox.xml' just adding the scroll buttons on the right of tab bar not messing with the \<arrowscrollbox\>.
I think for that you can just create buttons with js and use the css of \<arrowscrollbox\>.

Any success on this article?

**Comment by onemen** [comment]
Yes.

I have it working for normal tabs need more work for pinned tabs

**Comment by 117649** [comment]
Anything I can help with?
