### ISSUE TITLE
Multirows don't work after Firefox Nightly update

### ISSUE THREAD

**Issue by ozzyjr** [onemen/TabMixPlus#322]
After updating Firefox Nigthly this morning, I noticed that multirow stopped working. With the option activated, if the number of tabs is greater than the width of the browser window, instead of the tabs going to the bottom row, they become hidden and inaccessible. To view them again, I have to disable multirow.

Not work on Nightly 131.0a1 (2024-08-22) (64-bits)
Stills work on Developer Edition 130.0b8 (64-bits)
MacOs Sonoma 14.6.1

**Comment by pyrates999** [comment]
do NOT download that @ozzyjr

**Comment by onemen** [comment]
There are some changes i the latest Nightly, i will work on a fix this weekend

**Comment by onemen** [comment]
Download this [test build](https://github.com/user-attachments/files/16735831/test-build-1.22.1-20240824.1048.zip)

Rename it to `.xpi` and install it.

Report back

**Comment by vladko** [comment]
Works fine here now (Nightly 131.0a1 (2024-08-24) (64-bit)).
Just one issue: the new tab button (+) is sitting only on the top row, right. It does not want to be after the last tab.

**Comment by onemen** [comment]
Just one issue: the new tab button (+) is sitting only on the top row, right. It does not want to be after the last tab.

currently yes.
I must be on the top row when multi-row are in overflow, scroll buttons are visible on the right side, since the last row/tab can be hidden. 

i don't think it is necessary to show `new tab button` on both places

**Comment by onemen** [comment]
@vladko 

report if multi-row works for you on private window

**Comment by Shahius** [comment]
Unfortunately not working on 2nd window. 1st window is ok, but 2nd still not working.

**Comment by onemen** [comment]
Some Firefox Nightly methods changed yesterday ([Bug 1914519](https://bugzilla.mozilla.org/show_bug.cgi?id=1914519))

I will upload another test build later

**Comment by onemen** [comment]
This test build updates Tab Mix Plus code to follow the changes from:
- [Bug 1913322](https://bugzilla.mozilla.org/show_bug.cgi?id=1913322) - Make arrowscrollbox use resizeobserver rather than overflow/underflow events
- [Bug 1914332](https://bugzilla.mozilla.org/show_bug.cgi?id=1914332) - Consolidate arrowscrollbox horizontal & vertical property access
- [Bug 1914519](https://bugzilla.mozilla.org/show_bug.cgi?id=1914519) - Consolidate vertical mode and rtl checks in tab bar code

Download this [test build](https://github.com/user-attachments/files/16740263/test-build-1.22.1-20240825.1524.zip)

Rename it to `.xpi` and install it.

Report back

**Comment by onemen** [comment]
This test build updates Tab Mix Plus code to follow the changes from:
- [Bug 1913322](https://bugzilla.mozilla.org/show_bug.cgi?id=1913322) - Make arrowscrollbox use resizeobserver rather than overflow/underflow events
- [Bug 1914332](https://bugzilla.mozilla.org/show_bug.cgi?id=1914332) - Consolidate arrowscrollbox horizontal & vertical property access
- [Bug 1914519](https://bugzilla.mozilla.org/show_bug.cgi?id=1914519) - Consolidate vertical mode and rtl checks in tab bar code

Download this [test build](https://github.com/user-attachments/files/16740324/test-build-1.22.1-20240825.1552.zip)

Rename it to `.xpi` and install it.

Report back

**Comment by vladko** [comment]
Tabs work in the second window for me on windows 11. 
Thank you!

**Comment by onemen** [comment]
Download and install latest [development build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build)
