### ISSUE TITLE
Be careful with prefs-ce.js  

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#8]
I've just tried packing a new .xpi from [rewrite/main](https://github.com/onemen/TabMixPlus/tree/rewrite/main) after some css change. And the add-on option dialog window broken thus I have to revert most changes done on the 'prefs-ce.js'
Since the old add-on dialog is planed to be replaced may be just leave the file as it is.

#7

**Comment by onemen** [comment]
Beside the fix i suggested in #7, there are some bugs:

1. ```Uncaught (in promise) undefined``` (comment in prefs.ce.js), I think that this bug is what is crashing Firefox when trying to open option window from about:addons, we can not leave this issue open.
2. ```can't access property "getService", Components.classes['@mozilla.org/rdf/rdf-service;1'] is undefined session.js:854```
I will address this issue, I'm going to disable session manage until **complete** rewrite of it.
3. Some preferences are missing label or value when the preference window open:
   - Some preferences disable state dependent on other preferences, many are not correct after window load or when the controlling preference change state (checkbox clicked)
   - Links pane - 2nd menulist (id="divertedWindowOpen") is missing a label
   - Links pane - button (id="advancedSetting") should be disabled when checkbox (id="filetypeEnable") is not checked.
   - Links pane - Radiogroup (id="opentabforLinks)" is missing a value (one of the radio should be selected), both radio elements should be disabled when checkbox (id="forceLinkToTab") is not checked.
 4. Style for pref-filetype.xhtml is not working.
 5. Style for shortcut should be like this (when editing shortcut):
![image](https://user-images.githubusercontent.com/3650909/105016443-503aa600-5a4b-11eb-871f-cf26c127156f.png)
6. error when clicking on checkbox
 ```can't access property "checked", this._checkbox is undefined checkbox_tmp-ce.js:52
    get checked chrome://tabmixplus/content/preferences/checkbox_tmp-ce.js:52
    updateExternalLinkCheckBox chrome://tabmixplus/content/preferences/links.js:32
    anonymous chrome://tabmixplus/content/preferences/prefs-ce.js line 432 > Function:3
    setElementValue chrome://tabmixplus/content/preferences/prefs-ce.js:434
    updateElements chrome://tabmixplus/content/preferences/prefs-ce.js:540
    connectedCallback chrome://tabmixplus/content/preferences/prefs-ce.js:159
    connectedCallback chrome://tabmixplus/content/prefe
rences/prefs-ce.js:622
```
I will address the 2nd issue from the list.
Let me know if you can fix the first one and if you would like to work on the other issues

**Comment by 117649** [comment]
For first one: I've tried to fix when first time the thing breaks no success since. But it is neglectable in fact, there is a inline script in preferences.xhtml that will close the tab opened and open the dialog window if the file is opened in a tab. By not using overlay on about:addon this script will be put in power the drawback is a blank tab that is opened then immediately closed.  

For 3.1, 3.3 & 3.4 I.ve identified a typo that prevent broadcaster custom element been defined, this could be consider fixed mostly.
For 3.2 sorry I don't find the missing label I've counted there is in 3 total no one is missing. May be you are refer to that menulist selection box is empty while it not in enabled state? That just the style of the element now no idea on how to change that.

I can work on 4 and 5. 

For 6 need to know which checkbox is complaining.

Let me know where I should put the fix for 3.

**Comment by onemen** [comment]
Start new PR for issue 3 above

As for 3.2, when 'Use separate preference ...' is uncheck, the menulist is disabled, but the label 'New Tab' should still be visible
![image](https://user-images.githubusercontent.com/3650909/105049254-2302ed80-5a75-11eb-9bb9-0e708e51261f.png)
